services:
  postgres:
    image: postgres:16-alpine
    container_name: pismo-postgres
    environment:
      POSTGRES_USER: pismo
      POSTGRES_PASSWORD: pismo
      POSTGRES_DB: pismo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
